# Unique identifier for the run
run_id: "run_lr1e-4_32agents"

# Number of agents
N_AGENTS: 32

# Number of training steps to compile into the JAX jitted for loop 
# Practically it is the number of steps before metrics are computed
COMPILED_STEPS: 2000

# Total number of training steps to run 
TOTAL_TRAINING_STEPS: 50000

# Number of steps after which save an agent checkpoint
NUM_STEPS_CHECKPOINT: 10000

# Number of games to play to evaluate the agent
NUM_SNAKE_LENGHT_EVALUATIONS: 100

# Discount factor
GAMMA: 0.99

# Number of steps before params update
T_MAX: 5

# Entropy regularization factor
BETA: 0.01

# Clipping global norm
CLIP: 1

# Model type: 'nn' or 'linear'
MODEL_NAME: "nn"

# Learning rate for the optimizer
LR: 0.0001

# Clipping value for the optimizer
CLIP: 1.0

# Seed
SEED: 666
