from typing import Callable

import jax.numpy as jnp


def identity(x):
    return x


def compose_permutation(p: jnp.ndarray, q: jnp.ndarray) -> jnp.ndarray:
    """
    Compose permutations. First it applies q and then p
    """
    return q[p]


def compose_transformation(f: Callable, g: Callable) -> Callable:
    """
    Compose functions. First it applies g and then f
    """
    return lambda x: f(g(x))


def inverse_perm(perm: jnp.ndarray) -> jnp.ndarray:
    return jnp.argsort(perm)


def rot_90(x):
    return jnp.rot90(x, k=-1, axes=(0, 1))


def flip_updown(x):
    return jnp.flip(x, axis=0)


identity_perm = jnp.array([0, 1, 2, 3])  # R L D U
r90_perm = jnp.array([3, 2, 0, 1])  # U D R L
flip_updown_perm = jnp.array([0, 1, 3, 2])  # R L U D


def make_C2_flip_permutation_representation():
    """
    Cylic group (C2) permutation representation generated by an up-down flip
    """
    C2_updown_rep = {}

    C2_updown_rep["identity"] = (identity, jnp.array([0, 1, 2, 3]))
    C2_updown_rep["flip_updown"] = (flip_updown, jnp.array([0, 1, 3, 2]))

    return C2_updown_rep


def make_C2_rot_permutation_representation():
    """
    Cyclic group (C2) permutation representation generated by a 180 degree rotation
    """
    C2_rot_rep = {}

    C2_rot_rep["identity"] = (identity, jnp.array([0, 1, 2, 3]))
    C2_rot_rep["rot180"] = (
        lambda x: jnp.rot90(x, k=2, axes=(0, 1)),
        jnp.array([1, 0, 3, 2]),
    )

    return C2_rot_rep


def make_K4_permutation_representation():
    """
    Klein four-group (K4) permutation representation
    """
    K4_rep = {}

    K4_rep["identity"] = (identity, jnp.array([0, 1, 2, 3]))
    K4_rep["flip_updown"] = (flip_updown, jnp.array([0, 1, 3, 2]))
    K4_rep["flip_leftright"] = (lambda x: jnp.flip(x, axis=1), jnp.array([1, 0, 2, 3]))
    K4_rep["rot180"] = (
        lambda x: jnp.rot90(x, k=2, axes=(0, 1)),
        jnp.array([1, 0, 3, 2]),
    )

    return K4_rep


def make_C4_permutation_representation():
    """
    Cyclic group (C4) permutation representation generated by a 90 degree rotation
    """
    C4_rep = {}
    transformation = identity
    perm = jnp.array(range(4))
    for k in range(4):
        C4_rep[f"rot{90*k}"] = (
            transformation,
            perm,
        )

        transformation = compose_transformation(rot_90, transformation)
        perm = compose_permutation(r90_perm, perm)

    return C4_rep


def make_D4_permutation_representation():
    """
    Dihedral group (D4) permutation representation
    """
    D4_rep = {}
    transformation = identity
    perm = identity_perm
    for s in range(2):
        for k in range(4):
            D4_rep["flip_" * s + f"rot{90*k}"] = (
                transformation,
                perm,
            )

            transformation = compose_transformation(rot_90, transformation)
            perm = compose_permutation(r90_perm, perm)

        transformation = compose_transformation(flip_updown, transformation)
        perm = compose_permutation(flip_updown_perm, perm)

    return D4_rep
